name: ci

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Run tests
        working-directory: app
        run: go test ./...

      - name: Build docker image
        run: docker build -t devops-practice-api:${{ github.sha }} .